# ingrass.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-back-nj-portfolio-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
  - host: "api.tudominio.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-back-nj-portfolio-service
            port:
              number: 80
