# k8s/secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SECRET: "a3f8d7e0b2c94f1e6d5a8c2b7e3f9d01a4c6b8d2e5f7a3c9d1e0b4f6a8c2d7"
  MAIL_USER: "<tu_usuario_mailtrap>"
  MAIL_PASS: "<tu_contraseña_mailtrap>"
  FIREBASE_SERVICE_ACCOUNT_JSON: "asdf"
