apiVersion: v1
kind: Service
metadata:
  name: api-back-nj-portfolio-service
spec:
  selector:
    app: api-back-nj-portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
