apiVersion: v1
kind: Secret
metadata:
  name: api-back-secrets
  namespace: default
type: Opaque
stringData:
  SECRET: {{ .Values.secret.SECRET | quote }}
  MAIL_USER: {{ .Values.secret.MAIL_USER | quote }}
  MAIL_PASS: {{ .Values.secret.MAIL_PASS | quote }}
  FIREBASE_SERVICE_ACCOUNT_JSON: {{ .Values.secret.FIREBASE_SERVICE_ACCOUNT_JSON | quote }}
