# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [ main ]  # o la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar acceso SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Desplegar en EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/api-back-nj-portfolio
            git pull origin main
            npm install
            npm run build
            pm2 restart api-nestjs || pm2 start dist/main.js --name api-nestjs
          EOF
