# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Cambia si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Guardar clave privada en archivo
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Iniciar agente SSH y añadir clave
        run: |
          eval "$(ssh-agent -s)"
          ssh-add key.pem
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_HOST }}" > host.txt
          ssh-keyscan -H -f host.txt >> ~/.ssh/known_hosts

      - name: Desplegar en EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/api-back-nj-portfolio
            git pull origin main
            npm install
            npm run build
            pm2 restart api-nestjs || pm2 start dist/main.js --name api-nestjs
          EOF
